---
fabric:
  name: fabric-prod
  asn: 65088
  inventory:
    - seed_ip: 10.15.17.14
      auth_proto: MD5
      user_name: admin
      password: ""
      max_hops: 0
      role: spine
      preserve_config: false
    - seed_ip: 10.15.17.15
      user_name: admin
      password: ""
      max_hops: 0
      role: leaf
      preserve_config: false
    - seed_ip: 10.15.17.16
      user_name: admin
      password: ""
      max_hops: 0
      role: leaf
      preserve_config: false
