---
interface:
  vpc:
    - name: vpc10
      type: vpc
      switch:
        - 10.15.17.15
        - 10.15.17.16
      profile:
        admin_state: true
        mode: trunk
        peer1_members:
          - e1/1
        peer2_members:
          - e1/1
        pc_mode: 'active'
        bpdu_guard: true
        port_type_fast: true
        mtu: jumbo
    - name: vpc20
      type: vpc
      switch:
        - 10.15.17.15
        - 10.15.17.16
      profile:
          admin_state: true
          mode: trunk
          peer1_members:
            - e1/2
          peer2_members:
            - e1/2
          pc_mode: 'active'
          bpdu_guard: true
          port_type_fast: true
          mtu: jumbo
  loopback:
    - name: lo10
      type: lo
      switch:
        - 10.15.17.15
      profile:
        mode: lo
        int_vrf: "vrf_red"
        ipv4_addr: "10.10.10.101"
        route_tag: "12345"
    - name: lo10
      type: lo
      switch:
        - 10.15.17.16
      profile:
        mode: lo
        int_vrf: "vrf_red"
        ipv4_addr: "10.10.10.102"
        route_tag: "12345"
